### PR TITLE
Make API calls dynamic to load new data in production

### PR DESCRIPTION
**Pull request by D3nn7**
- bump nextjs to 13.4.3
- remove no longer needed experimental config from next.config.js
- resolve error that always the "Resolved" badge was displayed on an incident
- improve handling of isLoading, data and error in page.tsx
- add 'force-dynamic' rule configuration to router.ts so that data are refetched at production and not static generated
-  load github api calls parallel to avoid longer loading

### CODE REVIEW

**Comment by D3nn7** [comment]
@Jonas22rr The problem was, that nextjs only fetched data once because the API was static.
I also improved some other things according to data handling.

**Comment by D3nn7** [comment]
pls review. 
This is a **major fix** so that the status page works correctly in the future.

**Review by Jonas22rr — APPROVED** [review]
every thing fine for me but don`t know why you remove appdir from config

**Comment by D3nn7** [comment]
It's not needed anymore because it is stable and enabled by default.
Please approve.
Edit: like so
image

**Review by Jonas22rr — APPROVED** [review]
checked

**Pull request merged**
